### Part 1: Most expensive hospital for *Viral Meningitis*

The first goal of this sprint is to find which hospital charges the most for treating *Viral Meningitis*. We will be using the data file `hospital-costs.csv` located in the data folder.

The amount in the charge/costs columns is the price per discharge. Most hospitals treat many people with the same illness.  The amount they treat is the number in the "Discharges" column.

It is your job to calculate all the cost totals.

1. Create a new column "Total Charges" using "Discharges" and "Mean Charge".  
2. Do the same for the "Total Costs" using "Mean Cost".
2. With these two new "Total Charges" and "Total Costs" columns, calculate the charges to costs "markup" rate.
3. Tell me which facility has the highest "markup" rate, and which one has the lowest "markup" rate.  (It's always good to do a sanity check, do these results make sense to you?)

    Results:

    #### Lowest
    | Facility Name | ... | Total Charge | Total Cost | Markup|
    | ------------- |---|:-------------:| -----:|------|
    |TLC Health Network Tri-County Memorial Hospital | ...|  1540540    | 97482510  | 0.015803|

    #### Highest
    | Facility Name | ... | Total Charge | Total Cost | Markup|
    | ------------- |---|:-------------:| -----:|------|
    | SUNY Downstate Medical Center at LICH | ... | 43088   | 2068  | 20.835590|

In [73]:
import numpy as np
import pandas as pd

df = pd.read_csv("~/OneDrive/_mydev/galvanize/assignments/pandas/data/hospital-costs.csv")
#print(df.head())
#print(df.columns)
print(df)
# PART 1, STEP 1
df['Total Charges'] = df['Discharges'] * df['Mean Charge']

print(df['Total Charges'])

# PART 1, STEP 2
df['Total Costs'] = df['Discharges'] * df['Mean Cost']

print(df['Total Costs'])

# PART 1, STEP 3
df['Markup'] = df['Total Charges']/df['Total Costs']

# PART 1, STEP 4
# print(f'description: {df.describe().loc[:, "Markup"]}')

print(df['Markup'].min())
print(df.sort_values('Markup', ascending=True).loc[:, 'Markup'])
print(df['Markup'].max())
rint(df.sort_values('Markup').loc[:, 'Markup'])
#groups_markdown = df.groupby('Markup')
#rint(groups_markdown.min())
#print(groups_markdown.max())

# PART 2, STEP 1

        Year  Facility Id                                Facility Name  \
0       2011          324  Adirondack Medical Center-Saranac Lake Site
1       2011          324  Adirondack Medical Center-Saranac Lake Site
2       2011          324  Adirondack Medical Center-Saranac Lake Site
3       2011          324  Adirondack Medical Center-Saranac Lake Site
4       2011          324  Adirondack Medical Center-Saranac Lake Site
...      ...          ...                                          ...
383488  2009         1153            Wyoming County Community Hospital
383489  2009         1153            Wyoming County Community Hospital
383490  2009         1153            Wyoming County Community Hospital
383491  2009         1153            Wyoming County Community Hospital
383492  2009         1153            Wyoming County Community Hospital

        APR DRG Code  APR Severity of Illness Code  \
0                  4                             4
1                  5                             4
2                 24                             2
3                 26                             1
4                 41                             1
...              ...                           ...
383488           951                             3
383489           952                             3
383490           952                             2
383491           952                             1
383492           956                             0

                                      APR DRG Description  \
0       Tracheostomy W MV 96+ Hours W Extensive Proced...
1       Tracheostomy W MV 96+ Hours W/O Extensive Proc...
2                        Extracranial Vascular Procedures
3               Other Nervous System & Related Procedures
4                               Nervous System Malignancy
...                                                   ...
383488  Moderately Extensive Procedure Unrelated To Pr...
383489  Nonextensive Procedure Unrelated To Principal ...
383490  Nonextensive Procedure Unrelated To Principal ...
383491  Nonextensive Procedure Unrelated To Principal ...
383492                                        Ungroupable

       APR Severity of Illness Description APR Medical Surgical Code  \
0                                  Extreme                         P
1                                  Extreme                         P
2                                 Moderate                         P
3                                    Minor                         P
4                                    Minor                         M
...                                    ...                       ...
383488                               Major                         P
383489                               Major                         P
383490                            Moderate                         P
383491                               Minor                         P
383492                                 NaN                       NaN

       APR Medical Surgical Description  Discharges  Mean Charge  \
0                              Surgical           3     361289.0
1                              Surgical           1     102190.0
2                              Surgical           6      14172.0
3                              Surgical           1       8833.0
4                               Medical           1       5264.0
...                                 ...         ...          ...
383488                         Surgical           5      13572.0
383489                         Surgical           4       8323.0
383490                         Surgical           5       7746.0
383491                         Surgical           1       7892.0
383492                            Other           3       1069.0

        Median Charge  Mean Cost  Median Cost
0            210882.0   196080.0     123347.0
1            102190.0    59641.0      59641.0
2             13506.0     6888.0       6445.0
3              8833.0     4259.0       4259.0
4              5264.0     1727.0       1727.0
...               ...        ...          ...
383488        12615.0    14433.0      15835.0
383489         8179.0     9520.0       8674.0
383490         5120.0     7257.0       5321.0
383491         7892.0     6528.0       6528.0
383492         1309.0     1719.0       1756.0

[383493 rows x 14 columns]
0         1083867.0
1          102190.0
2           85032.0
3            8833.0
4            5264.0
            ...
383488      67860.0
383489      33292.0
383490      38730.0
383491       7892.0
383492       3207.0
Name: Total Charges, Length: 383493, dtype: float64
0         588240.0
1          59641.0
2          41328.0
3           4259.0
4           1727.0
            ...
383488     72165.0
383489     38080.0
383490     36285.0
383491      6528.0
383492      5157.0
Name: Total Costs, Length: 383493, dtype: float64
0.01580324511545712
370760     0.015803
370761     0.015894
370765     0.018554
370759     0.019447
370758     0.022474
            ...
239105    19.098654
367819    19.232660
367818    19.782071
111915    20.571158
111925    20.835590
Name: Markup, Length: 383493, dtype: float64
20.83558994197292

NameError: name 'rint' is not defined

In [95]:
df.columns()

TypeError: 'Index' object is not callable

In [96]:
df.loc[370760]

Year                                                                                2009
Facility Id                                                                           74
Facility Name                            TLC Health Network Tri-County Memorial Hospital
APR DRG Code                                                                         772
APR Severity of Illness Code                                                           1
APR DRG Description                    Alcohol & Drug Dependence W Rehab Or Rehab/Det...
APR Severity of Illness Description                                                Minor
APR Medical Surgical Code                                                              M
APR Medical Surgical Description                                                 Medical
Discharges                                                                           115
Mean Charge                                                                        13396
Median Charge                                                                      16159
Mean Cost                                                                         847674
Median Cost                                                                   1.0273e+06
Total Charges                                                                1.54054e+06
Total Costs                                                                  9.74825e+07
Markup                                                                         0.0158032
Name: 370760, dtype: object

In [74]:
df.loc[111925]

Year                                                                                2011
Facility Id                                                                         1302
Facility Name                                      SUNY Downstate Medical Center at LICH
APR DRG Code                                                                         614
APR Severity of Illness Code                                                           1
APR DRG Description                    Neonate Bwt 1500-1999G W Or W/O Other Signific...
APR Severity of Illness Description                                                Minor
APR Medical Surgical Code                                                              M
APR Medical Surgical Description                                                 Medical
Discharges                                                                             2
Mean Charge                                                                        21544
Median Charge                                                                      21544
Mean Cost                                                                           1034
Median Cost                                                                         1034
Total Charges                                                                      43088
Total Costs                                                                         2068
Markup                                                                           20.8356
Name: 111925, dtype: object

### Part 2: Out of curiosity
I wonder what everyone is going to the hospital for...
Use a groupby method on the 'APR DRG Description' column and sum the Discharges.

1.  What are the top 10 reasons people are going to the hospital for, and how many people did they see?

In [75]:
top10 = df.groupby('APR DRG Description').sum().sort_values('Discharges', ascending=False).head(10)

In [76]:
top10['Discharges']

APR DRG Description
Neonate Birthwt >2499G, Normal Newborn Or Neonate W Other Problem    632412
Vaginal Delivery                                                     458034
Cesarean Delivery                                                    245265
Heart Failure                                                        173826
Other Pneumonia                                                      162344
Septicemia & Disseminated Infections                                 161739
Chronic Obstructive Pulmonary Disease                                146461
Cellulitis & Other Bacterial Skin Infections                         124617
Cardiac Arrhythmia & Conduction Disorders                            121042
Chest Pain                                                           117630
Name: Discharges, dtype: int64

## Advanced

### Part 3: Follow the money

Now we want to see which hospital has the most money coming.
To keep this from getting messy, lets create a new DataFrame with only the columns we care about.  
1.  Create a new DataFrame named "net" that is only the Facility Name, Total Charges, Total Costs from our original DataFrame  
2.  Find the total amount each hospital spent, and how much they charged. (Group your data by Facility names, and sum all the total costs and total charges)  
3.  Now find the net income for every hospital. Tell me the most profitable and the least profitable ones and how much are they making?  


| Facility Name | Total Charge | Total Cost | Net Income |
|---|---|---|---|
| Adirondack Medical Center-Saranac Lake Site|141573499.0|77427664.0|64145835.0 |
| Albany Medical Center - South Clinical Campus|1802808.0|1432784.0|370024.0 |
| Albany Medical Center Hospital|3763945310.0|1336298908.0|2427646402.0 |
| Albany Memorial Hospital|221974029.0|94907174.0|127066855.0 |

In [ ]:
net = df[['Facility Name', 'Total Charges', 'Total Costs']]

In [78]:
net_income = net.groupby('Facility Name').sum()

In [79]:
net_income

,Total Charges,Total Costs
Facility Name,,
Adirondack Medical Center-Saranac Lake Site,1.415735e+08,7.742766e+07
Albany Medical Center - South Clinical Campus,1.802808e+06,1.432784e+06
Albany Medical Center Hospital,3.763945e+09,1.336299e+09
Albany Memorial Hospital,2.219740e+08,9.490717e+07
Alice Hyde Medical Center,8.723797e+07,4.105882e+07
...,...,...
Womans Christian Assoc Hospital - WCA Hosp at Jones Memorial Health Ce,1.604831e+07,9.527101e+06
Women And Children's Hospital Of Buffalo,8.629346e+08,3.732187e+08
Woodhull Medical & Mental Health Center,8.232658e+08,7.063462e+08
Wyckoff Heights Medical Center,1.191537e+09,5.056213e+08
Wyoming County Community Hospital,5.286328e+07,4.954708e+07

In [80]:
net_income['Net Income'] = net_income['Total Charges'] - net_income['Total Costs']

In [81]:
net_income

,Total Charges,Total Costs,Net Income
Facility Name,,,
Adirondack Medical Center-Saranac Lake Site,1.415735e+08,7.742766e+07,6.414584e+07
Albany Medical Center - South Clinical Campus,1.802808e+06,1.432784e+06,3.700240e+05
Albany Medical Center Hospital,3.763945e+09,1.336299e+09,2.427646e+09
Albany Memorial Hospital,2.219740e+08,9.490717e+07,1.270669e+08
Alice Hyde Medical Center,8.723797e+07,4.105882e+07,4.617915e+07
...,...,...,...
Womans Christian Assoc Hospital - WCA Hosp at Jones Memorial Health Ce,1.604831e+07,9.527101e+06,6.521212e+06
Women And Children's Hospital Of Buffalo,8.629346e+08,3.732187e+08,4.897160e+08
Woodhull Medical & Mental Health Center,8.232658e+08,7.063462e+08,1.169196e+08
Wyckoff Heights Medical Center,1.191537e+09,5.056213e+08,6.859159e+08
Wyoming County Community Hospital,5.286328e+07,4.954708e+07,3.316198e+06

In [82]:
net_income['Net Income'].max()

6050732279.0

In [83]:
net_income.max()

Total Charges    8.884406e+09
Total Costs      4.169593e+09
Net Income       6.050732e+09
dtype: float64

In [84]:
net_income.sort_values('Net Income', ascending=False)

,Total Charges,Total Costs,Net Income
Facility Name,,,
North Shore University Hospital,7.984556e+09,1.933824e+09,6.050732e+09
New York Presbyterian Hospital - Columbia Presbyterian Center,8.884406e+09,3.278723e+09,5.605683e+09
New York Presbyterian Hospital - New York Weill Cornell Center,6.889940e+09,2.543192e+09,4.346747e+09
Mount Sinai Hospital,7.321689e+09,3.069224e+09,4.252465e+09
Westchester Medical Center,6.095486e+09,2.047654e+09,4.047832e+09
...,...,...,...
"River Hospital, Inc.",2.175391e+06,3.497205e+06,-1.321814e+06
Rockefeller University Hospital,1.884305e+06,5.067838e+06,-3.183533e+06
Elizabethtown Community Hospital,8.988443e+06,1.251602e+07,-3.527574e+06
Catskill Regional Medical Center - G. Hermann Site,4.670920e+06,8.332317e+06,-3.661397e+06
TLC Health Network Tri-County Memorial Hospital,4.212448e+06,1.990285e+08,-1.948161e+08

In [85]:
net_income.sort_values('Net Income')

,Total Charges,Total Costs,Net Income
Facility Name,,,
TLC Health Network Tri-County Memorial Hospital,4.212448e+06,1.990285e+08,-1.948161e+08
Catskill Regional Medical Center - G. Hermann Site,4.670920e+06,8.332317e+06,-3.661397e+06
Elizabethtown Community Hospital,8.988443e+06,1.251602e+07,-3.527574e+06
Rockefeller University Hospital,1.884305e+06,5.067838e+06,-3.183533e+06
"River Hospital, Inc.",2.175391e+06,3.497205e+06,-1.321814e+06
...,...,...,...
Westchester Medical Center,6.095486e+09,2.047654e+09,4.047832e+09
Mount Sinai Hospital,7.321689e+09,3.069224e+09,4.252465e+09
New York Presbyterian Hospital - New York Weill Cornell Center,6.889940e+09,2.543192e+09,4.346747e+09
New York Presbyterian Hospital - Columbia Presbyterian Center,8.884406e+09,3.278723e+09,5.605683e+09
North Shore University Hospital,7.984556e+09,1.933824e+09,6.050732e+09

### Part 4: Focus in on *Viral Meningitis*
1. Create a new dataframe that only contains the data corresponding to *Viral Meningitis*  
    ```python
    
    newdf = df[df["APR DRG Description"] == "Viral Meningitis"]
    ```
2. Now, with our new dataframe, only keep the data columns we care about which are:  
    `["Facility Name", "APR DRG Description","APR Severity of Illness Description","Discharges", "Mean Charge", "Median Charge", "Mean Cost"]`

3. Our new dataframe should look somewhat like this:

    |Facility Name|APR DRG Description|APR Severity of Illness Description|Discharges|Mean Charge|Median Charge|Mean Cost|
    |----|----|----|----|----|----|----|
    |Adirondack Medical Center-Saranac Lake Site|Viral Meningitis|Minor|1|17116.0|17116.0|7006.0|
    |Albany Medical Center Hospital|Viral Meningitis|Minor|19|13212.0|11914.0|4569.0|
    |Albany Medical Center Hospital|Viral Meningitis|Moderate|11|21197.0|14197.0|7131.0|
    |Albany Medical Center Hospital|Viral Meningitis|Major|6|28074.0|22846.0|7495.0|


3. Find which hospital is the least expensive (based on "Mean Charge") for treating Moderate cases of VM. [*note example below is the most expensive not the least*]


    |Facility Name|APR DRG Description|APR Severity of Illness Description|Discharges|Mean Charge|Median Charge|Mean Cost|
    |----|----|----|----|----|----|----|
    |Beth Israel Med Center-Kings Hwy Div|Viral Meningitis|Moderate|1|71663.0|71663.0|12658.0|
    |Lutheran Medical Center|Viral Meningitis|Moderate|2|71850.0|71850.0|50605.0|
    |New York Presbyterian Hospital - Downtown Division|Viral Meningitis|Moderate|1|76528.0|76528.0|27563.0|
    |St Lukes Roosevelt Hospital - St Lukes Hospital Division|Viral Meningitis|Moderate|4|79245.0|48006.0|24743.0|
    |Orange Regional Medical Center|Viral Meningitis|Moderate|1|84003.0|84003.0|23143.0|


4. Find which hospital is the least expensive for treating Moderate cases of VM **that have more than 3 Discharges**.

    |Facility Name|APR DRG Description|APR Severity of Illness Description|Discharges|Mean Charge|Median Charge|Mean Cost|
    |----|----|----|----|----|----|----|
    |Cayuga Medical Center at Ithaca|Viral Meningitis|Moderate|6|5738.0|5111.0|3949.0|
    |Women And Children's Hospital Of Buffalo|Viral Meningitis|Moderate|31|6601.0|6182.0|2770.0|
    |Millard Fillmore Suburban Hospital|Viral Meningitis|Moderate|6|6614.0|6784.0|2649.0|

1. Find which hospital discharges the most cases of Viral Meningitis for all levels of severity.

    | Facility Name | ... | Discharges |
    | ------------- |-----|:----------:|
    | North Shore University Hospital | ... | 158 |
    | Montefiore Medical Center - Henry & Lucy Moses Div | ... | 152 |
    | Strong Memorial Hospital | ... | 117 |

1. Find if there is a correlation between the severity of illness and the charge. Hint use df.corr() *http://pandas.pydata.org/pandas-docs/stable/computation.html#correlation*

In [86]:
newdf = df[df["APR DRG Description"] == "Viral Meningitis"]

In [87]:
newdf.head()

,Year,Facility Id,Facility Name,APR DRG Code,APR Severity of Illness Code,APR DRG Description,APR Severity of Illness Description,APR Medical Surgical Code,APR Medical Surgical Description,Discharges,Mean Charge,Median Charge,Mean Cost,Median Cost,Total Charges,Total Costs,Markup
24,2011,324,Adirondack Medical Center-Saranac Lake Site,51,1,Viral Meningitis,Minor,M,Medical,1,17116.0,17116.0,7006.0,7006.0,17116.0,7006.0,2.443049
557,2011,1,Albany Medical Center Hospital,51,1,Viral Meningitis,Minor,M,Medical,19,13212.0,11914.0,4569.0,3920.0,251028.0,86811.0,2.891661
558,2011,1,Albany Medical Center Hospital,51,2,Viral Meningitis,Moderate,M,Medical,11,21197.0,14197.0,7131.0,3923.0,233167.0,78441.0,2.972514
559,2011,1,Albany Medical Center Hospital,51,3,Viral Meningitis,Major,M,Medical,6,28074.0,22846.0,7495.0,5812.0,168444.0,44970.0,3.745697
560,2011,1,Albany Medical Center Hospital,51,4,Viral Meningitis,Extreme,M,Medical,1,130600.0,130600.0,39086.0,39086.0,130600.0,39086.0,3.341350

In [88]:
newdf = newdf[["Facility Name", "APR DRG Description","APR Severity of Illness Description","Discharges", "Mean Charge", "Median Charge", "Mean Cost"]]

In [89]:
newdf

,Facility Name,APR DRG Description,APR Severity of Illness Description,Discharges,Mean Charge,Median Charge,Mean Cost
24,Adirondack Medical Center-Saranac Lake Site,Viral Meningitis,Minor,1,17116.0,17116.0,7006.0
557,Albany Medical Center Hospital,Viral Meningitis,Minor,19,13212.0,11914.0,4569.0
558,Albany Medical Center Hospital,Viral Meningitis,Moderate,11,21197.0,14197.0,7131.0
559,Albany Medical Center Hospital,Viral Meningitis,Major,6,28074.0,22846.0,7495.0
560,Albany Medical Center Hospital,Viral Meningitis,Extreme,1,130600.0,130600.0,39086.0
...,...,...,...,...,...,...,...
381587,Woodhull Medical & Mental Health Center,Viral Meningitis,Major,3,66690.0,28959.0,57219.0
382350,Wyckoff Heights Medical Center,Viral Meningitis,Minor,7,12588.0,10618.0,5470.0
382351,Wyckoff Heights Medical Center,Viral Meningitis,Moderate,2,7258.0,7258.0,3064.0
382352,Wyckoff Heights Medical Center,Viral Meningitis,Major,1,17336.0,17336.0,5653.0
383108,Wyoming County Community Hospital,Viral Meningitis,Major,1,4943.0,4943.0,3608.0

In [90]:
least_mean = newdf.sort_values('Mean Charge')

In [91]:
least_mean[least_mean["Discharges"] > 3]

,Facility Name,APR DRG Description,APR Severity of Illness Description,Discharges,Mean Charge,Median Charge,Mean Cost
76864,Olean General Hospital,Viral Meningitis,Minor,4,3601.0,3278.0,2014.0
52658,Memorial Hosp of Wm F & Gertrude F Jones A/K/A...,Viral Meningitis,Minor,5,3689.0,2829.0,1875.0
123661,Women And Children's Hospital Of Buffalo,Viral Meningitis,Minor,11,5417.0,5738.0,2273.0
14426,Cayuga Medical Center at Ithaca,Viral Meningitis,Moderate,6,5738.0,5111.0,3949.0
305294,Mary Imogene Bassett Hospital,Viral Meningitis,Minor,4,5821.0,4987.0,3710.0
...,...,...,...,...,...,...,...
57694,Montefiore Medical Center - Henry & Lucy Moses...,Viral Meningitis,Major,5,63565.0,33491.0,17686.0
331418,NYU Hospitals Center,Viral Meningitis,Major,5,64173.0,50730.0,21583.0
234825,St Lukes Roosevelt Hospital - St Lukes Hospita...,Viral Meningitis,Moderate,4,79245.0,48006.0,24743.0
122046,Winthrop-University Hospital,Viral Meningitis,Major,6,86414.0,71549.0,20291.0
49276,Maimonides Medical Center,Viral Meningitis,Major,5,87061.0,70834.0,27006.0

In [92]:
newdf.sort_values("Discharges", ascending=False).head(3)

,Facility Name,APR DRG Description,APR Severity of Illness Description,Discharges,Mean Charge,Median Charge,Mean Cost
73590,North Shore University Hospital,Viral Meningitis,Minor,34,25703.0,23285.0,5455.0
31399,Good Samaritan Hospital Medical Center,Viral Meningitis,Minor,33,18554.0,16488.0,6560.0
123662,Women And Children's Hospital Of Buffalo,Viral Meningitis,Moderate,31,6601.0,6182.0,2770.0

In [93]:
newdf['Discharges'].max()

34

In [94]:
newdf['Discharges'].max()

34

In [ ]:
print(df['APR Severity of Illness Description']) #.corr(df["Total Charges"])

## Extra Credit

### Part 6: Self-guided exploration

Continue exploring this data set, or find a data set online and explore

### Datasets
Ways to find a dataset

1. Choose one that you're already interested in.
2. Search [OpenPrism](http://openprism.thomaslevine.com) or any open data portal.
3. Use any of the following open datasets/portals
  * [DHS shelter residents](https://data.cityofnewyork.us/Social-Services/DHS-Daily-Report/k46n-sa2m?)
  * [Seattle 911 calls](https://data.seattle.gov/Public-Safety/Seattle-Real-Time-Fire-911-Calls/kzjm-xkqj)
  * [Alameda County Ficticious Business Names](https://data.acgov.org/Government/Alameda-County-Fictitious-Business-Names/cav4-k67f?)
  * [Baltimore 311 requests](https://data.baltimorecity.gov/City-Services/311-Customer-Service-Requests/9agw-sxsr)
  * [Montgomery Public Right Of Way Permits](https://data.montgomerycountymd.gov/Community/Public-Right-Of-Way-Permits/2b9e-mbxk)
  * [San Francisco](https://data.sfgov.org/)
  * __[Education](https://www.edsurge.com/n/2014-01-21-education-datapalooza)__

Additional datasets:
* [Government websites click throughs](http://www.usa.gov/About/developer-resources/1usagov.shtml)
* [Weather](http://www.wunderground.com/history/airport/KSFO/2014/1/6/DailyHistory.html)
* [SF neighborhoods](https://data.sfgov.org/Service-Requests-311-/Neighborhoods/ejmn-jyk6)
* [Zillow Rental](http://www.zillow.com/research/data/)
* [SF Two Bedroom home Sales](https://data.sfgov.org/Public-Health/Two-Bedroom-Home-Sales-from-2012-in-San-Francisco-/bw6b-qwhv) 
* [SF Rental Listings (6 Months)](https://data.sfgov.org/Public-Health/San-Francisco-Rental-Listings-06-2012-12-2012/c2ie-3fuy)
* [US Treasury](http://treasury.io/)
* __[Snacks!](http://www.snackdata.com/)__